### ISSUE TITLE
Autodeleter

### ISSUE THREAD

**Issue by n3oney** [httpreq/files.httpreq.club#1]
Yeah, the files must expire after some time. Therefore, we must do some things:
1. Add an expiry timestamp to [here](https://github.com/httpreq/files.httpreq.club/blob/main/src/index.ts#L71). @iraizo you know how to calculate it.
2. Add an interval that periodically checks for expired files. This should be easier because they're stored in the Database. http://mongodb.github.io/node-mongodb-native/3.6/api/GridFSBucket.html#delete

**Comment by iraizo** [comment]
being worked on.

**Comment by iraizo** [comment]
https://github.com/httpreq/files.httpreq.club/commit/c90af3760d1b98220c4abe739b7434f4a54f46fd https://github.com/httpreq/files.httpreq.club/commit/59b8ab8c41b1dc58d991d61bc0c851eb3717f0d8
